"""empty message

Revision ID: 320bff90ada1
Revises: 5489ad7b3964
Create Date: 2018-07-31 10:44:32.429242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '320bff90ada1'
down_revision = '5489ad7b3964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Integer(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user', sa.Column('role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role')
    op.drop_table('roles')
    # ### end Alembic commands ###
