"""empty message

Revision ID: 5489ad7b3964
Revises: fdfc467564cd
Create Date: 2018-07-30 16:15:51.636664

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5489ad7b3964'
down_revision = 'fdfc467564cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('nickname', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_nickname'), 'user', ['nickname'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_user_nickname'), table_name='user')
    op.drop_column('user', 'nickname')
    # ### end Alembic commands ###
